name: Deploy ASP.NET Core backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

env:
  AZURE_WEBAPP_NAME: FeedbackBackend
  AZURE_WEBAPP_PACKAGE_PATH: "." # the repository root
  DOTNET_VERSION: "3.1.102" # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@master

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet Test
      - name: dotnet test - run all tests
        run: dotnet test

      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          ls -a 
           dotnet build --configuration Release ./FeedbackBackend.sln 
           dotnet publish -c Release -o myapp ./FeedbackBackend.sln

      # Deploy to Azure Web apps
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp"
